engine:
  type: "in_memory"

servers:
  - type: tcp
    name: main
    port: 8080
    host: localhost
    max_connections: 5
    max_message_size: 4KB
    idle_timeout: 5m

  - type: console
    name:  console-service

logging:
  level: "debug"
  output: "output.log"

wal:
  flushing_batch_length: 100
  flushing_batch_timeout: "3s"
  max_segment_size: "4KB"
  data_directory: "wal_data"