engine:
  type: "in_memory"

servers:
  - type: tcp
    name: main
    port: 8080
    host: localhost
    max_connections: 1
    max_message_size: 4KB
    idle_timeout: 5m

  - type: console
    name:  console-service

logging:
  level: "info"
  output: "output.log"
